### ISSUE TITLE
Test keys warning: Use deployment check rather than RuntimeWarning?

### ISSUE THREAD

**Issue by PiDelport** [django-recaptcha/django-recaptcha#176]
Version 2.0.0 with PR #170 adds a `RuntimeWarning` when using the reCAPTCHA test keys. This is a good thing to check, but doing it this way has some downsides:

* It gets noisy when doing local development and testing, where the warning isn't usually relevant.
* It has to be explicitly silenced on CI builds that fail on warnings.

It may be better to move this to a Django deployment check ([docs](https://docs.djangoproject.com/en/2.1/topics/checks/#registering-and-labeling-checks)), so that the warning gets raised in a more relevant way?

**Comment by AltusBarry** [comment]
Thank your for you interest in this package and submitting this issue.

Unfortunately the check needs to happen during initialisation of each field as each field can be passed their own PRIVATE/PUBLIC key pair as well. Under most circumstances the fields are initialised once along with the forms, on process start, so the warnings should only be appearing once for each field.

Silencing the warnings should be a simple case of adding dummy PRIVATE and PUBLIC key values to the settings used during the CI testing. Unless this is not possible, for instance when running headless browser tests and need to bypass the V2 reCAPTCHA fallback challenge.

We can consider a setting: `RECAPTCHA_WARNINGS_TO_INFO` or something similar, to rather log the messages as info instead of issuing the warnings?

**Comment by pjdelport** [comment]
@AltusBarry: That's not a problem; in fact, that's a use case that Django's system check framework specifically supports and encourages:

* [Field, model, manager, and database checks](https://docs.djangoproject.com/en/2.2/topics/checks/#field-model-manager-and-database-checks)

**Comment by AltusBarry** [comment]
Goodness, apologies for not reading the docs properly. :sweat_smile: 

We will be making a new release as soon as possible, that includes this update.

**Comment by AltusBarry** [comment]
@pjdelport: We checked the docs again as well as skimming Django source. Seems the checks are only supported on model fields and not form fields.

Would it be possible to provide an example of the check framework integrated with form field checks?

**Comment by pjdelport** [comment]
Ah, hmm.

It would probably make most sense to limit this check to checking the value of the global settings? That's simpler, and handles the primary concern of users unintentionally or accidentally deploying to production with the default test keys.

When the keys are being dynamically passed directly to the constructor at runtime, the caller is doing it explicitly as an override, and I don't see that much utility in providing a warning about the default values in that case, right?

**Comment by AltusBarry** [comment]
Good point. We'll add a security check at app level.
Thanks.

**Comment by AltusBarry** [comment]
@pjdelport We have made a new release: 2.0.2

The check will however always trigger when the check framework kicks in, not just during deploy checks. It can be ignored using `SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']`

We hope this will make your life easier when it comes to those CI builds. :smiley:

**Comment by pjdelport** [comment]
@AltusBarry: Is there any strong reason for this not to be a deployment check, rather? It is production deployment specific condition, which is deploy flag for checks is meant for.

**Comment by AltusBarry** [comment]
@pjdelport: Truthfully, our own peace of mind. We have seen many a production deploy that does not run deployment checks in any phase of the process. 
Initially we wanted to ensure a user is always aware they are making use of the test creds Google provides, but conceded that it was overkill to also check in the event the values were explicitly passed to the field at runtime. The compromise is a check that had a well documented way of ignoring it.

We still want a check that will spare some poor overtaxed developer a headache, somewhere down the line, because someone did not document or request non test keys for their production deploys.

**Comment by thibaudcolas** [comment]
I believe this is… done? If not please let me know and we’ll re-open, or open a new issue clarifying what there might still be to improve.
