### ISSUE TITLE
omit some unnecessary

### ISSUE THREAD

**Issue by BamdadMeh** [django-recaptcha/django-recaptcha#284]
Hi , It's not a bug but a recommendation
It's better to remove type="text/javascript" from all JavaScript tags in  (js_v2_checkbox.html, js_v2_invisible.html, js_v3.html )
Because it's unnecessary

Thanks

**Comment by koutoftimer** [comment]
@BamdadMeh 

> It's better

Why?

From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type):

> [Attribute is not set (default), an empty string, or a JavaScript MIME type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type#attribute_is_not_set_default_an_empty_string_or_a_javascript_mime_type)
Indicates that the script is a "classic script", containing JavaScript code. Authors are encouraged to omit the attribute if the script refers to JavaScript code rather than specify a MIME type. JavaScript MIME types are [listed in the IANA media types specification](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript).

"Authors are encouraged" doesn't mean "it is better" to change existing code base. You can spend your time way better than arguing about this.

Also, I believe, you are encouraged to make a PR and it will be accepted with no friction.

**Comment by Stormheg** [comment]
Sure, next time please be constructive and don't formulate your response as a personal attack.

---

Let's go back on topic!

**Comment by Stormheg** [comment]
@alanverresen feel free to make a PR!

[95% of the sites out there use HTML according to w3techs](https://w3techs.com/technologies/overview/markup_language). We don't really care for XHTML support.

**Comment by Stormheg** [comment]
Closing as #324 is merged
